============================= test session starts ==============================
platform linux -- Python 3.6.10, pytest-4.6.2, py-1.8.0, pluggy-0.12.0 -- /home/angelo/anaconda3/envs/codenation/bin/python
cachedir: .pytest_cache
rootdir: /home/angelo/codenation/data-science-4
collecting ... collected 7 items

test_submit.py::test_q1 PASSED                                           [ 14%]
test_submit.py::test_q2 PASSED                                           [ 28%]
test_submit.py::test_q3 PASSED                                           [ 42%]
test_submit.py::test_q4 PASSED                                           [ 57%]
test_submit.py::test_q5 PASSED                                           [ 71%]
test_submit.py::test_q6 PASSED                                           [ 85%]
test_submit.py::test_q7 PASSED                                           [100%]

=============================== warnings summary ===============================
/home/angelo/anaconda3/envs/codenation/lib/python3.6/site-packages/statsmodels/tools/_testing.py:19
  /home/angelo/anaconda3/envs/codenation/lib/python3.6/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
    import pandas.util.testing as tm

-- Docs: https://docs.pytest.org/en/latest/warnings.html
---- generated xml file: /home/angelo/codenation/data-science-4/output.xml -----
===================== 7 passed, 1 warnings in 6.53 seconds =====================
